### PR TITLE
Issue 57 migrate to self hosted action runner

### LINKED ISSUE #57: Migrate to self-hosted action runner
## Prevent hitting monthly limit

... by using our own server for action processing.

## Description of a possible solution

Change `ubuntu-latest` to `self-hosted` `ubuntu` `Linux` or `16.04`

## Alternatives considered

Change runner keyword to `latest`, by that is misinforming since we run 16.04

### PR DESCRIPTION
**Pull request by Toeffe3**
## Purpose/Approach

Actions should run on our own server to prevent hitting the monthly limit cap for actions.

## Testing steps to find bugs or errors in added code.

- [x] Do the tests run?

### CODE REVIEW

**Comment by Toeffe3** [comment]
@Andreasgdp Why does CodeQL not run?

**Comment by Andreasgdp** [comment]
> @Andreasgdp Why does CodeQL not run?

Not only that, there are some actions that does not even run here. There should be at least 10 actions, and here there are only 7.

**Comment by Andreasgdp** [comment]
It looks to me like SonarCloud and CodeQL is not running, and that is why the total amt. of checks is only 7 and not 10.

When CodeQL runs correctly it will create a check more than the one present here that is waiting.

When SolarCloud runs it will create 2 checks.

This will bring the total up to 10 which is what we want.

**Comment by Andreasgdp** [comment]
I think I may have found the reason for why it doesn't run. In MealPlanr API these changes are not there and they are able to run CodeQL and SonarCube, so might be why

image
image

**Comment by Andreasgdp** [comment]
Looks like they are all being activated, but some are waiting for the server to respond leaving them in a limbo state. @Toeffe3 Any ideas?

**Review by Andreasgdp — APPROVED** [review]

**Pull request merged**
